#https://docs.docker.com/compose/compose-file/compose-versioning/
version: "3.7"

services:
  app:
    build: ./
    links:
      - 'redis'
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis

  redis:
    image: redis
    volumes:
          - redis_data:/data
    expose:
      - 6379
    ports:
      - 6379:6379

volumes:
  redis_data:
