version: "3.5"

services:
  app:
    build: ./
    depends_on:
      - redis
    environment:
      REDIS_URL: redis://redis

  redis:
    image: redis
    expose:
      - 6379
    ports:
      - 6379:6379
