#https://docs.docker.com/compose/compose-file/compose-versioning/
version: "3.3"

services:
  app:
    build: ./
    environment:
      - REDIS_HOST=redis
      - RHOST=redis
    networks:
      - redis-net
    depends_on:
      - redis
    ports:
      - 9000:9000
      - 9443:9443
    command: /svc/bin/start -Dhttps.port=9443 -Dredis.ip="$REDIS_IP" -Dplay.crypto.secret=secret

  redis:
    image: redis
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    networks:
      - redis-net
    volumes:
      - redis-data:/data
    ports:
      - 6379:6379

networks:
  redis-net:

volumes:
  redis-data:
